# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "efficient-customer-app"
client_id = "159d63e0445f71208173b8a4530d5916"
application_url = "https://sense-considerable-disease-combo.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sense-considerable-disease-combo.trycloudflare.com/auth/callback",
  "https://sense-considerable-disease-combo.trycloudflare.com/auth/shopify/callback",
  "https://sense-considerable-disease-combo.trycloudflare.com/api/auth/callback",
  "https://sense-considerable-disease-combo.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "asrasoft.myshopify.com"
